import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(publicSans.className, "dark")}>{children}</body>
    </html>
  );
}
